apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catatkeun.fullname" . }}-configmap
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "catatkeun.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
