apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.package.name }}-secret
  namespace: {{.Values.package.namespace}}
  labels:
    app: {{ .Release.Name }}
data:
  DATABASE_URL: {{ .Values.catatkeun.secret.DATABASE_URL | b64enc | quote }}
  AUTH_SECRET: {{ .Values.catatkeun.secret.AUTH_SECRET | b64enc | quote }}
  AUTH_GOOGLE_ID: {{ .Values.catatkeun.secret.AUTH_GOOGLE_ID | b64enc | quote }}
  AUTH_GOOGLE_SECRET: {{ .Values.catatkeun.secret.AUTH_GOOGLE_SECRET | b64enc | quote }}
  AUTH_TRUST_HOST: {{ .Values.catatkeun.secret.AUTH_TRUST_HOST | b64enc | quote }}
  AUTH_URL: {{ .Values.catatkeun.secret.AUTH_URL | b64enc | quote }}