apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catatkeun.fullname" . }}-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "catatkeun.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
