apiVersion: v1
kind: Service
metadata:
  name: {{ include "catatkeun.fullname" . }}-svc
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "catatkeun.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "catatkeun.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web-port
