apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.package.name}}-configmap
  namespace: {{.Values.package.namespace}}
  labels:
    app: {{.Release.Name}}
data:
  NEXT_PUBLIC_API_URL: "{{.Values.whoami.environment.API_URL | required "API_URL is required"}}"
