apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.package.name}}-secret
  namespace: {{.Values.package.namespace}}
  labels:
    app: {{.Release.Name}}
data:
  DATABASE_URL: {{.Values.whoami.secret.DATABASE_URL | b64enc | quote}}