package:
  name: catatkeun
  namespace: "catatkeun"
  image: "rootdavinalfa/catatkeun:7d5c378"
catatkeun:
  port: "3000"
  certificate:
    secretName: "catatkeun-cert"
  clusterIssuer: "letsencrypt-prod"
  ingressClass: "traefik"
  router:
    middleware: "default-redirect-https@kubernetescrd"
    host: "localhost"
  environment:
    API_URL: "http://localhost:3000"
  secret:
    DATABASE_URL: ""
    AUTH_SECRET : ""
    AUTH_GOOGLE_ID : ""
    AUTH_GOOGLE_SECRET : ""
    AUTH_TRUST_HOST : ""
  replica: 1
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 0

